# Generated by Django 3.2.20 on 2023-08-08 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20230808_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='m_or_f',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('U', 'Unisex')], max_length=254, null=True),
        ),
    ]
