# Generated by Django 3.2.20 on 2023-08-09 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_product_m_or_f'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='domain',
        ),
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Domain',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
